apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data:
  odoo.conf: |
    [options]
    db_host = postgres
    db_port = 5432
    db_user = odoo
    db_password = odoo
    addons_path = /usr/lib/python3/dist-packages/odoo/addons,/var/lib/odoo/addons/16.0,/mnt/extra-addons
    logfile = /var/log/odoo/odoo.log
