apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data:
  odoo.conf: |
    [options]
    db_host = postgres
    db_port = 5432
    db_user = odoo
    db_password = odoo
    logfile = /var/log/odoo/odoo.log
    admin_passwd = odoo
